### PR TITLE
add REDISQL.VERSION command

### PR DESCRIPTION
**Pull request by markuman**
add command `REDISQL.VERSION` to get the SQLite3 version which is used.

    127.0.0.1:6379> REDISQL.VERSION
    "3.14.2"

### CODE REVIEW

**Comment by siscia** [comment]
It is definitely necessary but I would like to change the syntax in `REDISQL.SQLITE_VERSION` more precise.

I prefer to avoid the inline returns.

**Comment by siscia** [comment]
Of course I modify your scripts to my needs myself, I already appreciate the idea.

However I must ask you to grant me all the rights to your contribution, you can simply state something like:

```
I hereby grant to Simone Mosciatti a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute my Contributions and such derivative works
```

**Comment by markuman** [comment]
Then why you've choosen AGPL as licence?

**Comment by siscia** [comment]
Actually there should not be any issues regarding the open source version, but since I am planning to sell not open source versions that may be based on the open one I just want to be sure to be completely covered from the legal point of view.

My motivation are explained in the readme as well.

I am trying to keep everything as smooth and simple as possible, I don't require people to sign CLA nor nothing.

However I do understand that you may don't want to grant me rights on your pull request, fell free to drop the PR.

**Comment by siscia** [comment]
@markuman other than the license constraint that are not fulfilled, as I mentioned earlier, I would prefer a slightly different syntax.

I am closing this pull request for now.

Said so I want to make sure that the project is as much transparent as possible.

The choice of the license is such to let everybody look at the code, to let other people study and to let them run it without any second thought.

I also really appreciated your PR and future contribution from you or from anybody else are extremelly welcome.

I need to iterate, however to the necessity to let me own the rights on any contribution on this same project. As I have stated I would like to dedicate as much energy and time to the project and to do so I would need to charge for some premium features, having some part of the codebase not under my complete control is a risk too high for me.

However, this does not mean that you cannot fork the project and create your own version.

I hope that I make myself clear.

Thank you.

**Pull request closed without merging**
